name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Formatting
      run: cargo fmt --all -- --check
    - name: Install wasm
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: Install Trunk
      uses: actions-rs/install@v0.1
      with:
        crate: trunk
        version: "0.16.0"
    - name: Build
      run: trunk build
      working-directory: ./satisfactory-accounting-app

